stages:
  - build
  - upload

build:
  stage: build
  image:
    name: ghcr.io/typst/typst:latest
    entrypoint: [""]
  script:
    - typst compile cheat_sheet.typ cheat_sheet.pdf --input REV=$CI_COMMIT_SHORT_SHA
  artifacts:
    paths:
      - cheat_sheet.pdf

upload-comsol:
  stage: upload
  image: curlimages/curl
  only:
    - main
  needs:
    - build
  script:
    - |
      curl https://exams.vis.ethz.ch/api/document/dschwaiger/cheatsheet-fs25/files/486/update/ \
        -H "Authorization: $TOKEN" \
        -F "file=@cheat_sheet.pdf" \
        -f
